### PR TITLE
[bugfix] fix issue #858 in CallDuplexConsensusReads

### LINKED ISSUE #858: Error in FilterConsensusReads
I get the same error as #847 while using v2.0.2

image

Code:
```
        fgbio -Xmx16g --async-io FilterConsensusReads  \
            -Djava.io.tmpdir=tmp  \
            --input=input  \
            --output=output  \
            --ref=ref \
            --min-reads=0 0 0 \
            --max-read-error-rate=0.05  \
            --max-base-error-rate=0.1  \
            --min-base-quality=50  \
            --max-no-call-fraction=0.05  \
            --require-single-strand-agreement=true
```

How the input to the above was generated:
```
        fgbio -Xmx16g --async-io CallDuplexConsensusReads  \
            -Djava.io.tmpdir=tmp  \
            --input=input  \
            --output=output  \
            --error-rate-pre-umi=45  \
            --error-rate-post-umi=30  \
            --min-input-base-quality=30
```
Also occurs with --min-reads=1 0 0

Here is that read:

image

### PR DESCRIPTION
**Pull request by nh13**
Fixes #858 where the AB strand single strand consensus read could have
zero depth and all Ns, such that the consensus read produced has an aD
value of zero but bD value > 0, causing issues in FilterConsensus Reads.

### CODE REVIEW

File: src/main/scala/com/fulcrumgenomics/umi/DuplexConsensusCaller.scala [hunk 1]
```diff
@@ -345,6 +345,10 @@ class DuplexConsensusCaller(override val readNamePrefix: String,
       case (None, Some(b))    => Some(DuplexConsensusRead(id=b.id, b.bases, b.quals, b.errors, b, None))
       case (Some(a), Some(b)) =>
         val len = min(a.length, b.length)
+        if (a.depths.take(len).forall(_ == 0)) {
+          require(b.depths.take(len).exists(_ > 0), "Bug: both consensus reads had zero depths across all bases")
+          return duplexConsensus(ba, ab, sourceReads)
+        }
```
Comment (nh13) [inline src/main/scala/com/fulcrumgenomics/umi/DuplexConsensusCaller.scala:351]: I don't like returns, but I don't see a way to structure the match better without some ugly refactoring.  Thoughts?

Comment (nh13) [reply src/main/scala/com/fulcrumgenomics/umi/DuplexConsensusCaller.scala:351]: Alternatively, we could change all single strand consensus reads that are all Ns to `None` we call `duplexConsensus`?

**Review by tfenne — APPROVED** [review]
Should we add a test too?
