### PR TITLE
Various HapCutToVcf updates

### LINKED ISSUE #414: HapCutToVcf should allow ambiguity codes in the reference
Hi, I recently tried to run HapCutToVcf on a VCF file, but it crashes with this error about a malformed VCF file:

```
$ java -jar fgbio-0.6.1.jar HapCutToVcf -v phased_variants.pass.vcf -i empty.hap -o try.vcf.gz
[2018/07/06 00:03:28 | FgBioMain | Info] Executing HapCutToVcf from fgbio version 0.6.1 as mschatz@yellowstone.cshl.edu on JRE 1.8.0_151-b12 with snappy
[2018/07/06 00:04:30 | FgBioMain | Info] HapCutToVcf failed. Elapsed time: 1.10 minutes.
Exception in thread "main" htsjdk.tribble.TribbleException: The provided VCF file is malformed at approximately line number 418615: unparsable vcf record with allele W, for input source: file:///home/mschatz/try/phased_variants.pass.vcf
	at htsjdk.variant.vcf.AbstractVCFCodec.generateException(AbstractVCFCodec.java:791)
	at htsjdk.variant.vcf.AbstractVCFCodec.checkAllele(AbstractVCFCodec.java:576)
	at htsjdk.variant.vcf.AbstractVCFCodec.parseAlleles(AbstractVCFCodec.java:538)
	at htsjdk.variant.vcf.AbstractVCFCodec.parseVCFLine(AbstractVCFCodec.java:341)
	at htsjdk.variant.vcf.AbstractVCFCodec.decodeLine(AbstractVCFCodec.java:284)
	at htsjdk.variant.vcf.AbstractVCFCodec.decode(AbstractVCFCodec.java:262)
	at htsjdk.variant.vcf.AbstractVCFCodec.decode(AbstractVCFCodec.java:64)
	at htsjdk.tribble.AsciiFeatureCodec.decode(AsciiFeatureCodec.java:70)
	at htsjdk.tribble.AsciiFeatureCodec.decode(AsciiFeatureCodec.java:37)
	at htsjdk.tribble.TribbleIndexedFeatureReader$WFIterator.readNextRecord(TribbleIndexedFeatureReader.java:372)
	at htsjdk.tribble.TribbleIndexedFeatureReader$WFIterator.next(TribbleIndexedFeatureReader.java:353)
	at htsjdk.tribble.TribbleIndexedFeatureReader$WFIterator.next(TribbleIndexedFeatureReader.java:314)
	at com.fulcrumgenomics.commons.CommonsDef$JavaIteratorAdapter.next(CommonsDef.scala:156)
	at scala.collection.Iterator.toStream(Iterator.scala:1403)
	at scala.collection.Iterator.toStream$(Iterator.scala:1402)
	at com.fulcrumgenomics.commons.CommonsDef$JavaIteratorAdapter.toStream(CommonsDef.scala:154)
	at scala.collection.Iterator.$anonfun$toStream$1(Iterator.scala:1403)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1169)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1159)
	at scala.collection.immutable.Stream.$anonfun$zip$1(Stream.scala:624)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1169)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1159)
	at scala.collection.immutable.StreamIterator.$anonfun$next$1(Stream.scala:1058)
	at scala.collection.immutable.StreamIterator$LazyCell.v$lzycompute(Stream.scala:1047)
	at scala.collection.immutable.StreamIterator$LazyCell.v(Stream.scala:1047)
	at scala.collection.immutable.StreamIterator.hasNext(Stream.scala:1052)
	at scala.collection.Iterator$$anon$1.hasNext(Iterator.scala:1075)
	at scala.collection.Iterator.isEmpty(Iterator.scala:374)
	at scala.collection.Iterator.isEmpty$(Iterator.scala:374)
	at scala.collection.AbstractIterator.isEmpty(Iterator.scala:1417)
	at com.fulcrumgenomics.vcf.HapCutAndVcfMergingIterator.hasNext(HapCutToVcf.scala:254)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at com.fulcrumgenomics.vcf.HapCutAndVcfMergingIterator.foreach(HapCutToVcf.scala:243)
	at com.fulcrumgenomics.vcf.HapCutToVcf.execute(HapCutToVcf.scala:113)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:99)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:80)
	at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:48)
	at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)
```

Looking at the VCF file, there is a 'W' to 'A' homozygous variant at this position:

```
$ sed -n '418615,418615p;418615q' phased_variants.pass.vcf
chr10	39316938	.	W	A	347.257	PASS	NS=1;DP=15;DPB=15.0;AC=2;AN=2;AF=1.0;RO=0;AO=20;PRO=0.0;PAO=0.0;QR=0;QA=180;PQR=0.0;PQA=0.0;SRF=0;SRR=0;SAF=2;SAR=3;SRP=0.0;SAP=3.44459;AB=0.333333;ABP=6.62942;RUN=1;RPP=6.91895;RPPR=0.0;RPL=1.0;RPR=4.0;EPP=3.44459;EPPR=0.0;DPRA=0.0;ODDS=16.5377;GTI=0;TYPE=snp;CIGAR=3M1X;NUMALT=2;MEANALT=2.0;LEN=1;MQM=60.0;MQMR=0.0;PAIRED=0.8;PAIREDR=0.0;technology.ILLUMINA=1.0;VCFALLELICPRIMITIVE;MUMAP_REF=31.0;MUMAP_ALT=60.0;MMD=2.08122;RESCUED=0;NOT_RESCUED=20;HAPLOCALLED=0	GT:BX:PS	1|1:,TATCTCATCAGAGGAC-1_69;TGTGGTATCCTCGCTA-1_47;CTGTTTACATGGTAAA-1_47;GACGGCTCATTAGCCA-1_69;TGCTACCAGTTGCAGG-1_69;GTTGCAATCTCCTGTG-1_65;GTCTCGTAGTGGAGTC-1_69;AGCCGACCACTTGAGT-1_69;GTTCTCGGTCACGCCA-1_69;GAGCAGAAGAATTCGA-1_69_69;CGAACTAAGGCTAAAT-1_69;ACTGTCCAGTACGTTC-1_69;CCACTGTAGCCACATT-1_69;CAGTGTACACTGTCGG-1_69_69;GCAACCGCAACGCCGT-1_69_69;TAGCCGGCAGACGAGT-1_47:38580966
```

I think this should be allowed, since it is correcting an ambiguity code that is present in the reference hg38 (this shows it as an N, but it is a 'W' in the fasta file):
http://genome.ucsc.edu/cgi-bin/das/hg38/dna?segment=chr10:39316918,39316958

The VCF file is available here:
http://labshare.cshl.edu/shares/schatzlab/www-data/encode/10x/version2/ENC-0002/phased_variants.pass.vcf

The error can be triggered with an empty hapcut file (I first hit it with a real hapcut file)
$ echo > empty.hap

Thanks!

Mike

### PR DESCRIPTION
**Pull request by nh13**
Fixes #414 and #415

### CODE REVIEW

File: src/main/scala/com/fulcrumgenomics/vcf/HapCutToVcf.scala [hunk 1]
```diff
@@ -117,6 +123,32 @@ class HapCutToVcf
     vcfWriter.close()
   }
 
+  /** If fixing ambiguous (IUPAC) bases is desired, returns a new path to a VCF, otherwise returns the original input VCF. */
+  private def inputVcf: FilePath = if (!fixAmbiguousReferenceAlleles) this.vcf else {
```
Comment (tfenne) [inline src/main/scala/com/fulcrumgenomics/vcf/HapCutToVcf.scala]: Could you move this above `execute()` please?

File: src/main/scala/com/fulcrumgenomics/vcf/HapCutToVcf.scala [hunk 2]
```diff
@@ -117,6 +123,32 @@ class HapCutToVcf
...
+
+    val inputLines = PathUtil.extensionOf(this.vcf) match {
+      case Some(".vcf") => Io.readLines(this.vcf)
+      case Some(".vcf.gz")  =>
+        val stream = Io.toInputStream(this.vcf)
```
Comment (tfenne) [inline src/main/scala/com/fulcrumgenomics/vcf/HapCutToVcf.scala]: Doesn't `Io.readLines` also work for gzipped files?  If not we should make it, because it _should_.

File: src/main/scala/com/fulcrumgenomics/vcf/HapCutToVcf.scala [hunk 3]
```diff
@@ -117,6 +123,32 @@ class HapCutToVcf
...
+        Source.fromInputStream(stream).withClose(() => stream.close()).getLines()
+      case Some(".bcf") => throw new IllegalArgumentException(s"BCF not supported when fixing ambiguity codes in: ${this.vcf}")
+      case _            => throw new IllegalArgumentException(s"Could not determine file type from ${this.vcf}")
+    }
+    val outputLines = inputLines.map { line =>
```
Comment (tfenne) [inline src/main/scala/com/fulcrumgenomics/vcf/HapCutToVcf.scala]: Super lame that you have to do this and write to a file and can't filter on the fly and have VCFFileReader read from a  stream :/

File: src/main/scala/com/fulcrumgenomics/vcf/HapCutToVcf.scala [hunk 4]
```diff
@@ -117,6 +123,32 @@ class HapCutToVcf
...
+      if (line.startsWith("#")) line else {
+        val items = line.split('\t')
+        val bases = items(3).map { base =>
```
Comment (tfenne) [inline src/main/scala/com/fulcrumgenomics/vcf/HapCutToVcf.scala]: Two thoughts - does this handle both ref and alts?  I.e. what if you had a deletion or insertion containing ambiguity codes?  Secondly, do you need to make sure you're not in a symbolic allele like `<REF>`?

File: src/main/scala/com/fulcrumgenomics/vcf/HapCutToVcf.scala [hunk 5]
```diff
@@ -126,7 +158,12 @@ class HapCutToVcf
       .setOption(Options.INDEX_ON_THE_FLY)
       .setOption(Options.WRITE_FULL_FORMAT_FIELD)
       .setOption(Options.ALLOW_MISSING_FIELDS_IN_HEADER)
-    val writer: VariantContextWriter = builder.build
+    val writer: VariantContextWriter = if (this.createIndex) {
+      builder.setOption(Options.INDEX_ON_THE_FLY).build
```
Comment (tfenne) [inline src/main/scala/com/fulcrumgenomics/vcf/HapCutToVcf.scala]: Could we not auto-fill the right answer as true if the output is bgzipped or bcf or (plain VCF but the input has contig lines)?  It sounds, based on the issue, like this is automatable and then we don't have to pass the buck to the user.

File: src/main/scala/com/fulcrumgenomics/vcf/HapCutToVcf.scala (hunk 2 above)
Comment (nh13) [reply src/main/scala/com/fulcrumgenomics/vcf/HapCutToVcf.scala]: Fixed

File: src/main/scala/com/fulcrumgenomics/vcf/HapCutToVcf.scala (hunk 4 above)
Comment (nh13) [reply src/main/scala/com/fulcrumgenomics/vcf/HapCutToVcf.scala]: Yup, wasn't handling alts, but now we are.  Symbolic alleles are skipped, I forgot about those.

File: src/main/scala/com/fulcrumgenomics/vcf/HapCutToVcf.scala (hunk 5 above)
Comment (nh13) [reply src/main/scala/com/fulcrumgenomics/vcf/HapCutToVcf.scala]: Buck is now not passed.

File: src/main/scala/com/fulcrumgenomics/vcf/HapCutToVcf.scala (hunk 1 above)
Comment (nh13) [reply src/main/scala/com/fulcrumgenomics/vcf/HapCutToVcf.scala]: Done

File: src/main/scala/com/fulcrumgenomics/vcf/HapCutToVcf.scala (hunk 3 above)
Comment (nh13) [reply src/main/scala/com/fulcrumgenomics/vcf/HapCutToVcf.scala]: :/

**Comment by nh13** [comment]
@tfenne one last look are are you good?
